### PR TITLE
Refactor setting pop up

### LINKED ISSUE #23: Fix Settings Popup Responsiveness/Positioning
Need help with this.
When I add more settings in the popup, it runs out of room and the audio slider at the bottom doesn't show up anymore. I couldn't make it scrollable either.

### PR DESCRIPTION
**Pull request by kat066**
==Changelog==
- Make font size stay in a readable size
- Refactor css so that it is easy to add more settings
- Fixes issue https://github.com/kat066/biglunchbox-pomodoro/issues/23

==Testing==
- Local simulation test

==Version Compatibility==
- N/A

==Detail Description==
- Referred to login pop up in various website (google, geekforgeeks,
  etc), made font size and pop up size constant.
- Refactor the display structure so that it is easy to add more settings
 Screenshot 2022-05-17 145538
Screenshot 2022-05-18 172500

### CODE REVIEW

**Review by bl-rr — DISMISSED** [review]
Not my expertise but seems good to me

**Comment by Juhmer-Tena** [comment]
Passes the tests but has responsive issues with vertical screens. 
image. I think this might have to do with the use of pixels for styling.

**Comment by broiyn** [comment]
Not sure why it happens, but this shows up when I first load/refresh the page. Then if I click the settings icon it goes back to normal and everything works fine. Not sure if anyone else has this issue or maybe I just need a browser update, but other than that it works great.

image

**Comment by kat066** [comment]
> Not sure why it happens, but this shows up when I first load/refresh the page. Then if I click the settings icon it goes back to normal and everything works fine. Not sure if anyone else has this issue or maybe I just need a browser update, but other than that it works great.
> 
> image

This is caused by refreshing using ctrl+shift+r. It kind of messes up the order of how things show up. normal refresh should be fine.

**Comment by bl-rr** [comment]
CI is failing :(

**Comment by kat066** [comment]
> CI is failing :(

Weird, passed locally.

**Comment by kat066** [comment]
This failing test is related to task list.

**Comment by kat066** [comment]
@broiyn @Binghong-Leo-Li @AxiosDeminence CI error introduced in previous commits. Not sure why it passed before. I fixed it anyway in this PR. Please review again. Release blocker.

**Comment by broiyn** [comment]
> > Not sure why it happens, but this shows up when I first load/refresh the page. Then if I click the settings icon it goes back to normal and everything works fine. Not sure if anyone else has this issue or maybe I just need a browser update, but other than that it works great.
> > image
> 
> This is caused by refreshing using ctrl+shift+r. It kind of messes up the order of how things show up. normal refresh should be fine.

It's still happening to me and I'm just clicking refresh. Is there any other reason it might happen? If I'm the only one with this problem then maybe it's fine?

**Comment by kat066** [comment]
> > > Not sure why it happens, but this shows up when I first load/refresh the page. Then if I click the settings icon it goes back to normal and everything works fine. Not sure if anyone else has this issue or maybe I just need a browser update, but other than that it works great.
> > > image
> > 
> > 
> > This is caused by refreshing using ctrl+shift+r. It kind of messes up the order of how things show up. normal refresh should be fine.
> 
> It's still happening to me and I'm just clicking refresh. Is there any other reason it might happen? If I'm the only one with this problem then maybe it's fine?

I see it now, let me see what is happening.

**Review by broiyn — APPROVED** [review]
awesome, settings popup looking great now!

**Comment by Juhmer-Tena** [comment]
As mentioned per Slack DMs, mentioned bugs in this PR were fixed and everything LGTM now.

**Review by Juhmer-Tena — APPROVED** [review]

**Pull request merged**
