### PR TITLE
Refactor home page UI

### PR DESCRIPTION
**Pull request by kat066**
==Changelog==
- Refactor home page UI to make it responsive
- Fixes issue #53

==Testing==
- Local simulation testing

==Version Compatibility==
- N/A

==Detail Description==
- Put everything in flex box, use global variables for various constants
- Use media query for different dimensions
-
Screenshot 2022-05-26 012349
Screenshot 2022-05-26 012405

### CODE REVIEW

**Review by zianlin — DISMISSED** [review]
Don't see any problems on my end, seems great

**Review by zianlin — DISMISSED** [review]
Read over the changes and it looks great, only see improvements

**Comment by Binghong-Leo-Li** [comment]
Should be good after fixing CI

**Review by bl-rr — DISMISSED** [review]
Such great work! But this may not have been the intention? But maybe I'm wrong and this is design decision though?

Screen Shot 2022-05-30 at 09 53 34

**Comment by bl-rr** [comment]
Among the 3 servers started by "npm start", one of them had the "dim out" for the buttons appearing during "non-focused" mode instead of focused ones. Not sure why that happened or how to trigger it. Not sure if it is caused by this update either. But maybe of interest to find out why

Screen Shot 2022-05-30 at 10 06 18
Screen Shot 2022-05-30 at 10 08 09
Screen Shot 2022-05-30 at 10 06 14

**Review by brooksniu — APPROVED** [review]
Looks good, responsiveness and overlapping issues are fixed.

**Review by Juhmer-Tena — APPROVED** [review]
LGTM

**Pull request merged**
