### PR TITLE
Use artifacts coverage and assets

### PR DESCRIPTION
**Pull request by Juhmer-Tena**
==Changelog==
- ~Added artifacts upload during pull requests to dev~
- ~Added artifacts download for push to master~
- Relaxed Cypress caching keys

==Testing==
- Forked repo testing

==Version Compatibility==
- All versions compatible including sprite sheet versions using assets.

==Detail Description==
- Cypress will now cache between workflow runs (and maybe use dev branch)
- ~Downloading artifacts from dev for master is fine since we require branches to be up to date before merging them to dev.~

### CODE REVIEW

**Review by brooksniu — DISMISSED** [review]
Looks fine, but we need to merge it into dev to know if there is any potential problem

**Comment by Juhmer-Tena** [comment]
Had to nix artifact uploads for use in deployment because it was getting complicated sharing artifacts between branches and ensuring the correct artifact is fetched. Cypress caching is still improved though.

**Review by brooksniu — APPROVED** [review]
lgtm, reducing complexity for stability is for sure a worthy trade-off

**Review by Totay — APPROVED** [review]
lgtm

**Pull request merged**
