### PR TITLE
Created a completed task view

### PR DESCRIPTION
**Pull request by Totay**
==Changelog==
- There is now a button to toggle between seeing completed and
incomplete tasks
- changed script and TaskItem tests to pass

==Testing==
- Tested checking and uncheck tasks to see if it would disappear from
view and reappear in the correct view
- Manually tested moving a task from incomplete to complete, then back.
- Manually tested moving a task from incomplete and focus to see if it
goes to the completed task. Then clicking to set it to go to incomplete
and focus again

==Version Compatibility==
- None

==Detail Description==
- Added menu element with the toggle buttons in it
- button switches color through toggling button attributes and CSS
selector
- TaskItem no longer uses line-through CSS properties but instead just
hides display
- Brighten TaskItem on hover to indicate hover

### CODE REVIEW

**Review by Burniee — APPROVED** [review]
Just tested it out myself, seems to work aside from the fact when I refresh the page, any completed tasks will become blank, but it's probably not that big of a deal. Aside from that, we'll just have to update the tests to match the new feature, but aside from that. LGTM

**Review by Burniee — DISMISSED** [review]
Sorry, was gonna retract my approval due to the completed tasks being blank after a refresh, but tested it for a bit more, and if you put the completed task back into the "Up next" section again, and refresh the page, the task comes back.

**Comment by broiyn** [comment]
image

Jimmy already mentioned it, but yeah if I refresh the page this happens on the completed tasks. Not sure if it's just an issue with displaying the text or maybe if it has something to do with retrieving the names of the tasks from localStorage? Because like jimmy said if you move the task back to uncompleted and refresh again, then the text reappears.

**Review by broiyn — APPROVED** [review]
Nice, it's working for me now, tests are passing, nothing bad jumping out at me in your code.

**Review by Burniee — APPROVED** [review]
All good for me too!

**Pull request merged**
