### PR TITLE
Added setting to show remaining time on tab

### PR DESCRIPTION
**Pull request by broiyn**
==Changelog==
- added a function to change site title when the time is updated
- added toggle for tab label to settings pop up
- added setting info to localstorage

==Testing==
- manually checked that remaining time is displayed only when toggle is on
- manually checked that setting choices persist after refreshing the page
- automated tests not done yet

==Version Compatibility==

==Detail Description==
- added updateTabLabel() function in Timer.js which checks localstorage and updates
  the title element if the setting is turned on
- copied the same format from the dark mode toggle to add a tab label
  toggle to the settings template
- added toggleTabLabel() method in SettingsPopUp.js (and binded to tab
  label toggle)
- updated tests that were broken from adding the toggle
- still waiting for kai's fix to the settings popup to be merged to dev

### CODE REVIEW

**Comment by broiyn** [comment]
Here is what it looks like:
image
image

**Comment by brooksniu** [comment]
Code is clean. I think there will be no conflicts with others' code.

**Review by brooksniu — APPROVED** [review]
Code is clean. I think there will be no conflicts with others' code.

**Review by Burniee — APPROVED** [review]
Added code is clean, seems like you tested it well, LGTM

**Pull request merged**
