### PR TITLE
Updated focus mode, updated timer graphics, fixed color bug, updated Cypress Tests

### LINKED ISSUE #40: Hide Buttons on Focus Mode & Auto Switch to Focus Mode on Timer Start & test timer graphics
Change button opacity (or display:hidden) to hide buttons, probably needs to rearrange position after hiding other buttons for better UX. 

Make line coverage in jest 100%. Add test for uncovered lines related to timer graphics.

### PR DESCRIPTION
**Pull request by brooksniu**
==Changelog==

Updated focus mode, updated timer graphics, fixed color bug, updated Cypress Tests

==Testing==

all test passed

==Version Compatibility==

All compatible. No deletion of code.

==Detail Description==

Updated focus mode where the timer automatically goes into focus mode when timer begins. 
While in focus mode the buttons are less visible to promote focus.
Updated timer graphics to be draining when in pomo mode, filling when in break mode. 
Updated top buttons hover to highlight when in focus mode.
Fixed bug: when switching themes with timer running, the filling color within timerDisplay does not change accordingly.
Updated cypress tests to fit new changes.
Adjusted timer graphics to be filled when initialized instead of empty.
Updated timer graphics theme color logics to ensure consistency when there are multiple classes in body (from using body class to local storage theme state).

closes issue #40

### CODE REVIEW

**Review by Totay — CHANGES_REQUESTED** [review]
image
- Can you make it so that the color is filled up when the timer isn't on.
- Also, in focus mode, when you hover over the icons, can you make the hovered icons opaque, not transparent. having the user click on a transparent button doesn't signal to them that you can click it. just make the hovered button opaque not the entire menu buttons

image
the timer on light mode is still the dark color

**Comment by brooksniu** [comment]
> image
> 
> * Can you make it so that the color is filled up when the timer isn't on.
> * Also, in focus mode, when you hover over the icons, can you make the hovered icons opaque, not transparent. having the user click on a transparent button doesn't signal to them that you can click it. just make the hovered button opaque not the entire menu buttons
> 
> image the timer on light mode is still the dark color

The issue was my branch was not up-to-date with dev branch. I merged from dev and adjusted accordingly. Should be gtg now!

**Comment by brooksniu** [comment]
Changed the detection of color theme to using localstorage's theme attribute instead of checking length of classlist. Increases stability.

**Review by broiyn — APPROVED** [review]
nothing problematic jumping out at me, and it seems to work fine on my machine

**Review by Totay — APPROVED** [review]
Everything fixed

**Pull request merged**
