### PR TITLE
Revamped and standardized old JSDocs.

### PR DESCRIPTION
**Pull request by zianlin**
The old documentation had many undocumented functions and a lot of copy-paste, non-helpful messages for the ones that were documented. I've taken the liberty to standardize them all and provide helpful information of every function used.

### CODE REVIEW

**Review by broiyn — CHANGES_REQUESTED** [review]
It looks like these commits make several changes to the actual code, not just documentation. I tried running the app locally and the popups won't even open anymore with these changes. I'm guessing these weren't intentional and maybe something went wrong when resolving merge conflicts with dev?

**Comment by zianlin** [comment]
> It looks like these commits make several changes to the actual code, not just documentation. I tried running the app locally and the popups won't even open anymore with these changes. I'm guessing these weren't intentional and maybe something went wrong when resolving merge conflicts with dev?

That's really weird: must've been working on an older version of the codebase? Regardless, I've updated the code in all files to match the most recent changes in /dev/ and fixed all the linting errors, so it should be good to merge now.

**Review by bl-rr — DISMISSED** [review]
I experienced the same issue as Brian before but seems like everything is fixed now

**Comment by bl-rr** [comment]
Also, try to test CI locally first before submitting. That way it would be easier for you to fix tests

**Review by broiyn — APPROVED** [review]
looks good now

**Review by broiyn — APPROVED** [review]

**Review by Totay — APPROVED** [review]
good job !

**Pull request merged**
