### PR TITLE
Timer Reset Warning (#9)

### LINKED ISSUE #9: Timer Reset Warning
# Design Use Case

- Description: When the user goes into the settings, there is an indicator/warning for users that the timer will be stopped if they edit the session length settings if the timer is ongoing.
- User/Designer Goal: Users do not accidentally reset the timer or do not get confused when the timer resets after editing the session length settings.
- Desired Outcome: Users get an explicit indicator (ie. text) that the timer will reset when the session length settings get changed.
- Workflow: 
  1. User opens settings pop-up
  2. Users sees warning and knows any consequences of editing the timer settings
  3. User changes settings and confirms.
  4. Localstorage information gets updated and timer is reset to new values.
- Alternative Workflows
  iii. User cancels changing settings or closes the settings panel without confirming.
  iv. Localstorage information is not updated and timer settings are unchanged when re-opening the settings panel.

## Relevant ADRs
- [User Warnings for Timer Settings](https://github.com/kat066/biglunchbox-pomodoro/blob/408e6eeac4ee9a8004cab96271d0e9ee58e77c23/specs/adrs/042922-UserWarningTimerSettingsEdit.md)

### PR DESCRIPTION
**Pull request by Burniee**
==Changelog==
-Added warning message to setting popup

==Testing==
-Jest and Cypress tests pass

==Version Compatibility==
-Full Compatibility, since nothing crazy was changed in the code to warrant any compatibility issues

==Detail Description==
-Updated setting popup menu to reflect the fact that any changes to settings will cause a reset in timer

EDIT: OKAY, I was having a lot of problems trying to revert the previous commit from Friday, so I just created a new branch from dev and remade the changes. Hopefully it works this time or I'ma cry

### CODE REVIEW

**Review by kat066 — DISMISSED** [review]
Code looks lgtm.

**Comment by Burniee** [comment]
Sorry, took a bit to fix all the conflicts, finished up.

**Comment by Burniee** [comment]
Ah shit
edit: 
please don't send me to the goober for these commits

**Review by broiyn — DISMISSED** [review]

**Review by Totay — DISMISSED** [review]
blame juhmer

**Comment by broiyn** [comment]
juhmer said it's good and i trust him

**Review by Totay — APPROVED** [review]
blame juhmer electric boogaloo version

**Review by broiyn — APPROVED** [review]
juhmer said it's good and i trust him

**Pull request merged**
