### PR TITLE
smoothened animation, added timer graphics, fixed tests, fixed videos

### PR DESCRIPTION
**Pull request by brooksniu**
==Changelog==

Created my branch on main repo (for easier fixes)
Smoothened button animations.
Added timer graphics.
Changed Brian's Timer Label from using the minutes/seconds variables to parsed ints from TimerDisplay, which adds stability because the timer relies on calling "minutes" and "seconds" to increment the value.

==Testing==

All tests passed.

==Version Compatibility==

N/A

==Detail Description==

Smoothened button scaling animations, added timer graphics (filling from bottom-up in timer display section). One option is gradually fill up the entire page.

==Potential Improvements==

Let the user choose the graphic's color. Background image customization.
Toogle for whole page graphics/timer display graphics.

### CODE REVIEW

**Review by broiyn — DISMISSED** [review]
Code looks consistent with the existing style, don't see anything crazy going on, tests are passing. Nice.

**Comment by Juhmer-Tena** [comment]
LGTM. Pretty good. The only thing I'd ask is if we could squash the two commits (feature commit and merge commit) together then that'd be helpful in keeping the commit history clean.

**Comment by brooksniu** [comment]
> LGTM. Pretty good. The only thing I'd ask is if we could squash the two commits (feature commit and merge commit) together then that'd be helpful in keeping the commit history clean.

Thanks for the feed back. Squashing the commits will definitely make the history cleaner. I just tried to squash in Github Desktop but a merge commit cannot exist between two commits if we want to squash them. Here the merge button is "squash and merge" so I think we would be able to squash the PR when merging.

**Review by Juhmer-Tena — APPROVED** [review]
Thought I clicked approve earlier, my bad.

**Review by broiyn — APPROVED** [review]

**Pull request merged**
